name: pixelfield_test
description: My new Flutter app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  bloc: ^9.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  hive_flutter: ^1.1.0
  get_it: ^9.2.0
  equatable: ^2.0.7
  flutter_phoenix: ^1.1.1
  permission_handler: ^12.0.1
  go_router: ^17.0.1
  logger: ^2.6.2
  toastification: ^3.0.3
  flutter_svg: ^2.2.3
  cached_network_image: ^3.4.1
  dio: ^5.9.1
  smooth_page_indicator: ^2.0.1
  shimmer: ^3.0.0
  flutter_local_notifications: ^19.5.0
  hive: ^2.2.3
  google_fonts: ^6.3.3
  youtube_player_flutter: ^9.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  intl_utils: ^2.8.8
  hive_generator: ^2.0.1
  very_good_analysis: ^10.0.0
  build_runner: ^2.4.13

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/vectors/
    - assets/images/
    - assets/mock/
